### ISSUE TITLE
Unexpected token: keyword (const) by UglifyJs

### ISSUE THREAD

**Issue by karolisgrinkevicius-home24** [roderickhsiao/react-aspect-ratio#15]
Hey. Thanks for this great tiny library. When bundling entire app with Webpack I'm getting an error about unexpected usage of `const` in `dist/es/index.js` from `UglifyJs`. Could this be fixed to use `var` instead of `const`?

**Comment by roderickhsiao** [comment]
Thanks for reaching out

Several issues I could see

1 `UglifyJs` won't work for es module, suggested to use `[terser](https://github.com/terser-js/terser)`, which is a fork of `uglify-es (not maintained) - and break lots of React bundling`, webpack already move away default minifier to `terser` instead.
1. you could try to alias `react-aspect-ratio/es` to `react-aspect-ratio` in webpack, which will load the [cjs bundle ](https://unpkg.com/react-aspect-ratio@1.0.40/dist/react-latest.js) instead of es bundle
1. You can also include this library in your webpack file so it can be transpile via babel alone with your application code before minify the code. 

Hope it helps

**Comment by karolisgrinkevicius** [comment]
@roderickhsiao yeah, thanks for your quick response. I switched further to terser plugin and now have everything working nicely. 👍

**Comment by roderickhsiao** [comment]
Yes, there is a huge discussion in open source community as many people found issues on `uglify` and `uglify-es` (even `babel-minifiy`), and currently the safest way is just switch to terser
